server {
    listen 80;
    server_name localhost;

    root /var/www/src/public;
    index index.php index.html;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; object-src 'none'; frame-ancestors 'none';" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;
    }

    client_max_body_size 500M;
}

# server {
#     listen 80;
#     server_name namsifl.uz www.namsifl.uz;
#     return 301 https://$host$request_uri;
# }

# server {
#     listen 443 ssl;
#     server_name namsifl.uz www.namsifl.uz;

#     ssl_certificate /etc/ssl/namsifl/namsifl_uz.crt;
#     ssl_certificate_key /etc/ssl/namsifl/namsifl_uz.key;

#     root /var/www/namsifl/src/public;
#     index index.php index.html index.htm;

#     add_header X-Frame-Options "SAMEORIGIN" always;
#     add_header Content-Security-Policy "default-src 'self'; script-src 'self'; object-src 'none'; frame-ancestors 'none';" always;
#     add_header X-XSS-Protection "1; mode=block" always;
#     add_header X-Content-Type-Options "nosniff" always;
#     add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
#     add_header Referrer-Policy "no-referrer-when-downgrade" always;
#     add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

#     # Laravel routing (eng muhim qism)
#     location / {
#         try_files $uri $uri/ /index.php?$query_string;
#     }

#     # PHP ishlashi uchun
#     location ~ \.php$ {
#         include fastcgi_params;
#         fastcgi_pass unix:/var/run/php/php8.4-fpm.sock;  # o'zingiznikiga moslashtiring
#         fastcgi_index index.php;
#         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#     }

#     # Yashirin fayllar va .env ni himoya qilish
#     location ~ /\.(?!well-known).* {
#         deny all;
#     }

#     # storage va bootstrap/cache ga tashqaridan kirishni taqiqlash
#     location ~ ^/(storage|bootstrap/cache)/ {
#         deny all;
#     }

#     # Statik fayllar uchun cache (ixtiyoriy)
#     location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot)$ {
#         expires 30d;
#         add_header Cache-Control "public";
#     }

#     # Loglar (kerak bo'lsa)
#     access_log /var/log/nginx/namsifl_access.log;
#     error_log /var/log/nginx/namsifl_error.log;
# }